name: fothema_companion
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  convex_bottom_bar: ^3.2.0
  english_words: ^4.0.0
  provider: ^6.0.0
  permission_handler: ^11.3.1
  universal_ble: ^0.13.0
  path_provider: ^2.1.5
  webview_flutter: ^4.10.0
  toastification: ^2.3.0

fonts:
- family: RobotoMono
  fonts:
  - asset: fonts/roboto_mono.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
